### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Skysparko**
1. add media query for responsiveness
2. in button i changed btn div to grid for make the button responsive
3. changed bg image and put aqua color
4. added every element into a box to give it a look like card and added color and shadow to it

### CODE REVIEW

**Comment by Skysparko** [comment]
@Aman0786-git I hope you like it.

**Comment by aman999au** [comment]
> @Aman0786-git I hope you like it.

Can you please provide SS of the UI Changes

**Comment by Skysparko** [comment]
sure
BlackJack - Brave 03-10-2022 16_35_30

**Comment by aman999au** [comment]
Thankyou for contributing

**Pull request merged**
