### PR TITLE
UI changes(Uniformity in Color Scheme) #9

### PR DESCRIPTION
**Pull request by amyra98**
Before :
BlackJack - Google Chrome 03-10-2022 16_54_46
After :
BlackJack - Google Chrome 03-10-2022 18_25_03

### CODE REVIEW

**Comment by amyra98** [comment]
@Aman0786-git

**Comment by aman999au** [comment]
> @Aman0786-git

It will be better if you can just fit all the content in one page like you dont have to scroll so let me know if can fix that and if so then make a PR with the changes

**Comment by amyra98** [comment]
I have done those changes @Aman0786-git 
BlackJack - Google Chrome 03-10-2022 21_02_42

**Comment by aman999au** [comment]
Thankyou @amyra98

**Pull request merged**
